server {
    listen 443 ssl;
    server_name proxy;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;

    client_max_body_size 10m;

    location / {
        proxy_pass http://conjur;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
